// <auto-generated />
using Course_Site.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Course_Site.Migrations
{
    [DbContext(typeof(Academy))]
    partial class AcademyModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Course_Site.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("FacultyId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            FacultyId = 1,
                            Title = "C# 10 and .NET 6"
                        },
                        new
                        {
                            FacultyId = 2,
                            Title = "Web Development"
                        },
                        new
                        {
                            FacultyId = 3,
                            Title = "Python for Beginners"
                        });
                });

            modelBuilder.Entity("Course_Site.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Alice",
                            LastName = "Jones"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Bob",
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Cecilia",
                            LastName = "Ramirez"
                        });
                });

            modelBuilder.Entity("FacultyStudent", b =>
                {
                    b.Property<int>("FacultiesFacultyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentsStudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FacultiesFacultyId", "StudentsStudentId");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("FacultyStudent");

                    b.HasData(
                        new
                        {
                            FacultiesFacultyId = 1,
                            StudentsStudentId = 1
                        },
                        new
                        {
                            FacultiesFacultyId = 1,
                            StudentsStudentId = 2
                        },
                        new
                        {
                            FacultiesFacultyId = 1,
                            StudentsStudentId = 3
                        },
                        new
                        {
                            FacultiesFacultyId = 2,
                            StudentsStudentId = 2
                        },
                        new
                        {
                            FacultiesFacultyId = 3,
                            StudentsStudentId = 3
                        });
                });

            modelBuilder.Entity("FacultyStudent", b =>
                {
                    b.HasOne("Course_Site.Models.Faculty", null)
                        .WithMany()
                        .HasForeignKey("FacultiesFacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Course_Site.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
