// <auto-generated />
using Course.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Programming_CoursesDataContext.Migrations
{
    [DbContext(typeof(Programming_CoursesContext))]
    [Migration("20220623130116_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Course.Shared.ProgrammingCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INT IDENTITY(1,1)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("FutureJob")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL");

                    b.HasKey("CourseId");

                    b.ToTable("Programming_Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
